### ISSUE TITLE
Typo on message.required

### ISSUE THREAD

**Issue by crediblebytes** [yariksav/vuetify-confirm#11]
Message is not required due to misspelling of 'required' in code:
`message: {
      type: String,
      reqiured: true
    },`

**Comment by yariksav** [comment]
Hi, @goodies4uall! Thank you! I will fix this

**Comment by sundus-y** [comment]
This pull request should fix the issue. #12

**Comment by yariksav** [comment]
Thank you, @sundus-y for PR

**Comment by davellanedam** [comment]
I'm getting this:

vue.js:634 [Vue warn]: Missing required prop: "message"
