### ISSUE TITLE
Missing required prop: "message"

### ISSUE THREAD

**Issue by davellanedam** [yariksav/vuetify-confirm#13]
I'm getting this:

vue.js:634 [Vue warn]: Missing required prop: "message"

I see the same message on your demo.

Thanks!

**Comment by yariksav** [comment]
Hi, @davellanedam! Thank you for your issue!
fixed in 84fffeb5f04e049265cbcf725cf0932c761692ce
please update to 0.2.4 version

**Comment by davellanedam** [comment]
Awesome work! Thank you so much, working great now.
