### ISSUE TITLE
persistent

### ISSUE THREAD

**Issue by mttmccb** [yariksav/vuetify-confirm#14]
It would be great if this plugin supported `persistent` so you have to make a selection, currently clicking outside is the same as the negative option which might be not be what you want.

You can see it here https://vuetifyjs.com/en/components/dialogs#

**Comment by yariksav** [comment]
Hi, @mttmccb. Nice request. Please try new version 0.2.5 ;)

**Comment by yariksav** [comment]
Closed by c0bcc24df50b36bd13624a6c4dddd9e03e166de3

**Comment by leowin** [comment]
Would be fine, if "persistent" would also be part of Typescript definitions
