### ISSUE TITLE
Errors when using with latest vue/vuetify

### ISSUE THREAD

**Issue by garyo** [yariksav/vuetify-confirm#15]
It works fine, but I see these errors in the JS console:
```
vue.runtime.esm.js?2b0e:619 [Vue warn]: Missing required prop: "message"
(found in <Root>)
```
It happens at line 7 of index.js where the component is first created. The `message` prop isn't passed into the component there, only on the next line (line 13):
```javascript
      const cmp = new Vue(Object.assign(Confirm, {
        destroyed: (c) => {
          document.body.removeChild(cmp.$el)
          resolve(cmp.value)
        }
      }))
      Object.assign(cmp, Vue.prototype.$confirm.options || {}, options)
```
Perhaps a null message (or the actual one) could be passed in to the initial construction to prevent that error?

**Comment by yariksav** [comment]
Hi, @garyo. This error already solved in #13. I guess you use old version of module. Please use latest 0.2.5
npm i vuetify-confirm@latest

**Comment by garyo** [comment]
Ha, thanks -- you're too fast! 😄 Thanks!

**Comment by yariksav** [comment]
Best wishes! :)
