### ISSUE TITLE
confirm did not support with vuetify current version

### ISSUE THREAD

**Issue by mean-cj** [yariksav/vuetify-confirm#21]
Hello

i cannot add vuetify-confirm to nuxt
the vuetify-confirm did not support with vuetify current version

                                                                                                             friendly-errors 21:11:47
 @ ./node_modules/vuetify/src/components/VDataTable/VDataTableHeader.sass 4:14-215 14:3-18:5 15:22-223
 @ ./node_modules/vuetify/lib/components/VDataTable/VDataTableHeader.js
 @ ./node_modules/vuetify/lib/components/VDataTable/index.js
 @ ./node_modules/vuetify/lib/components/index.js
 @ ./node_modules/vuetify/lib/index.js
 @ ./node_modules/vuetify-confirm/dist/vuetify-confirm.js
 @ ./plugins/vuetify.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true&timeout=30000&ansiColors=&overlayStyles=&name=client&path=/__webpack_hmr/client ./.nuxt/client.js

**Comment by yariksav** [comment]
Hi, @mean-cj. If you want to get help, you have to give a detailed description. Because vuetify-confirm works with vuetify 1 and 2 as well. Perhaps you did wrong usage of it

**Comment by mean-cj** [comment]
Hello @yariksav 

Thank you for your project.

i will found error vuetify-confirm and vuetify-dialog is not work 
when i load vuetify last version only on nuxt plugin

i found error message
```
in ./node_modules/vuetify/src/components/VSparkline/VSparkline.sass
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Invalid CSS after "    @content": expected "}", was "($material-light); "
```

but  vuetify-confirm and vuetify-dialog it work
when i load @nuxtjs/vuetify on nuxt.config.js 
buildModules: [
    '@nuxtjs/vuetify',
]

Thank you so much.

**Comment by yariksav** [comment]
![image](https://user-images.githubusercontent.com/2553313/68076602-72e98c00-fdbf-11e9-93e6-64f263bbdb30.png)
Please check correct installation in your nuxt project, and update to vuetify-confirm@2.0.1 version

**Comment by mean-cj** [comment]
Hello @yariksav

this problem i found same with #vuetify-dialog 

If someone else found same problem , can include on nuxt module
https://github.com/yariksav/vuetify-dialog#%EF%B8%8F-usage-with-nuxtjs

Thank your so much.
